package com.hybrid.framework.runners;

import com.hybrid.framework.config.ConfigReader;
import io.cucumber.testng.AbstractTestNGCucumberTests;
import io.cucumber.testng.CucumberOptions;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.testng.annotations.DataProvider;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Re-runs only the failed Cucumber scenarios from the previous execution.
 * <p>
 * Reads the failed scenario paths from {@code target/rerun.txt}, which is
 * generated by the {@code rerun} plugin configured in {@link TestRunner}.
 * </p>
 *
 * <b>Controlled by:</b>
 * <ul>
 *   <li>{@code bdd.rerun.enabled=true|false} in config.properties (default: true)</li>
 *   <li>Runtime override: {@code -Dbdd.rerun.enabled=false}</li>
 * </ul>
 *
 * When disabled or when {@code target/rerun.txt} is empty/missing,
 * this runner returns zero scenarios and effectively becomes a no-op.
 */
@CucumberOptions(
        features = "@target/rerun.txt",
        glue = {"com.hybrid.framework.stepdefs"},
        plugin = {
                "pretty",
                "html:target/cucumber-reports/rerun-cucumber.html",
                "json:target/cucumber-reports/rerun-cucumber.json",
                "io.qameta.allure.cucumber7jvm.AllureCucumber7Jvm",
                "com.hybrid.framework.reporting.ExtentCucumberPlugin"
        },
        monochrome = true
)
public class FailedScenariosRunner extends AbstractTestNGCucumberTests {

    private static final Logger LOG = LogManager.getLogger(FailedScenariosRunner.class);
    private static final Path RERUN_FILE = Path.of("target/rerun.txt");

    //creating directories and files if they don't exist
    //so that the rerun file is created if it doesn't exist and does not throw an exception
    //if not present then new file creted is empty and hence no scenarios are rerun
    static {
        try {
            Files.createDirectories(RERUN_FILE.getParent());
            if (!Files.exists(RERUN_FILE)) {
                Files.createFile(RERUN_FILE);
            }
        } catch (IOException e) {
            LogManager.getLogger(FailedScenariosRunner.class)
                    .warn("Could not ensure rerun file exists: {}", e.getMessage());
        }
    }

    @Override
    @DataProvider(parallel = true)
    public Object[][] scenarios() {
        boolean rerunEnabled = ConfigReader.getInstance()
                .getBoolean("bdd.rerun.enabled", true);

        if (!rerunEnabled) {
            LOG.info("BDD rerun is disabled (bdd.rerun.enabled=false). Skipping failed scenario retry.");
            return new Object[0][0];
        }

        if (!hasFailedScenarios()) {
            LOG.info("No failed scenarios found in {}. Nothing to rerun.", RERUN_FILE);
            return new Object[0][0];
        }

        LOG.info("Re-running failed scenarios from {}", RERUN_FILE);
        return super.scenarios();
    }

    private boolean hasFailedScenarios() {
        try {
            return Files.exists(RERUN_FILE)
                    && Files.size(RERUN_FILE) > 0
                    && !Files.readString(RERUN_FILE).isBlank();
        } catch (IOException e) {
            LOG.warn("Could not read {}: {}", RERUN_FILE, e.getMessage());
            return false;
        }
    }
}
